"""empty message

Revision ID: 80199bdd7f29
Revises: 1d533e173c36
Create Date: 2026-03-17 11:14:52.126764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80199bdd7f29'
down_revision = '1d533e173c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
